apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

commonLabels:
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace/argocd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.1/manifests/install.yaml

patches:
  - path: configmap/argocd-cm.yaml
  - path: configmap/argocd-cmd-params-cm.yaml